INSERT INTO Cidade (nomeCidade) VALUES ('Porto Alegre');
INSERT INTO Cidade (nomeCidade) VALUES ('Sao Paulo');
INSERT INTO Cidade (nomeCidade) VALUES ('Florianopolis');
INSERT INTO Cidade (nomeCidade) VALUES ('Restinga Seca');
INSERT INTO Cidade (nomeCidade) VALUES ('Cacapava do Sul');
INSERT INTO Bairro (nomeBairro, custoBasico, cidade) VALUES ('Partenon', 50, Cidade(Porto Alegre));
INSERT INTO Bairro (nomeBairro, custoBasico, cidade) VALUES ('Rio Branco', 80, Cidade(Porto Alegre));
INSERT INTO Bairro (nomeBairro, custoBasico, cidade) VALUES ('Moinhos de Vento', 100, Cidade(Porto Alegre));
INSERT INTO Propriedade(id, custo, cidade, bairro, cep, endereco, indicada, classificacao) VALUES ('1', 150, Cidade(Porto Alegre), Bairro(Rio Branco), '90430-175', 'Rua General Paula Macedo', 'FAMILIA','LUXO');
INSERT INTO Cliente(cpf, dataNascimento, formaPagamento, statusCliente, orcamento, cidadeCliente) VALUES ('052414214', '27-05-1989', 'DEBITO', 'CASAL', 'LUXO', Cidade(Porto Alegre));